### ISSUE TITLE
Failure to load the texture of the cross origin

### ISSUE THREAD

**Issue by cx20** [playcanvas/playcanvas-gltf#9]
I tried to access [github's resource](http://github.com/cx20/gltf-test/) from [RawGit](https://rawgit.com/) service from [jsdo.it](http://jsdo.it/).

http://jsdo.it/cx20/4b3J

However, because of the cross origin restriction, it could not be displayed.
```javascript
playcanvas-latest.js:5280 
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.
    at GraphicsDevice.uploadTexture (https://cdn.rawgit.com/cx20/gltf-test/e63efa65/libs/playcanvas/v0.223.0-dev/playcanvas-latest.js:5280:16)
    at GraphicsDevice.setTexture (https://cdn.rawgit.com/cx20/gltf-test/e63efa65/libs/playcanvas/v0.223.0-dev/playcanvas-latest.js:5386:12)
    at GraphicsDevice.draw (https://cdn.rawgit.com/cx20/gltf-test/e63efa65/libs/playcanvas/v0.223.0-dev/playcanvas-latest.js:5446:14)
    at ForwardRenderer.drawInstance (https://cdn.rawgit.com/cx20/gltf-test/e63efa65/libs/playcanvas/v0.223.0-dev/playcanvas-latest.js:9957:14)
    at ForwardRenderer.renderForward (https://cdn.rawgit.com/cx20/gltf-test/e63efa65/libs/playcanvas/v0.223.0-dev/playcanvas-latest.js:10549:21)
    at ForwardRenderer.render (https://cdn.rawgit.com/cx20/gltf-test/e63efa65/libs/playcanvas/v0.223.0-dev/playcanvas-latest.js:10895:10)
    at Application.render (https://cdn.rawgit.com/cx20/gltf-test/e63efa65/libs/playcanvas/v0.223.0-dev/playcanvas-latest.js:20677:16)
    at https://cdn.rawgit.com/cx20/gltf-test/e63efa65/libs/playcanvas/v0.223.0-dev/playcanvas-latest.js:20995:13
```

The resources you attempted to access are as follows.
https://cdn.rawgit.com/cx20/gltf-test/e63efa65/tutorialModels/FlightHelmet/glTF/FlightHelmet.gltf

Perhaps when accessing via RawGit, you can access it by specifying `anonymous` as the crossOrigin attribute. 
```javascript
img.crossOrigin = "anonymous";
```

Please provide a way to access the resources of the cross origin constraint with playcanvas-gltf.

**Comment by cx20** [comment]
I confirmed that the resources of the cross origin constraint can be displayed by the latest version library.

[![image](https://user-images.githubusercontent.com/1833979/37560567-5bac3cb0-2a7e-11e8-9f71-99fcab420557.png)](http://jsdo.it/tag/PlayCanvas)

I think that this correspondence is useful also in CodePen and JSFiddle.
